#!/usr/bin/perl -w

use strict;
use warnings;
use Data::Dumper;
use IOTAlib;

$| = 1;

if (scalar(@ARGV) != 4)
{
    print "Usage:\n";
    print "./getbalance <URL> <port> <password> <address>\n";
    print "\n";
    print "<URL> is the URL of server with IRI\n";
    print "<port> is the apiPort of IRI from configuration.iri\n";
    print "<password> is the apiPassword from configuration.iri\n";
    print "<address> is the IOTA address\n";
    print "\n";
    print "Example:\n";
    print "\n";
    print "./getbalance localhost 999 mypwd PYCUDAXRCRLDNSJZLWZEHXDDTAOK9OTZPWKKCDHSKLFEBRMPWRRTTVDSPKZ9CICLWJZEWQ9PVCUZTTZFP\n";
    print "\n";
    die;
}

# --------------------------------
$IOTAlib::port = $ARGV[1];
$IOTAlib::host = $ARGV[0];

my $tips = IOTAlib::POST({ 'command' => 'getTransactionsToApprove',
                             'password' => $ARGV[2] });

my $res = IOTAlib::POST({ 'command' => 'getBalances',
                            'addresses' => [$ARGV[3]],
                            'tips' => $tips->{'hashes'},
                            'password' => $ARGV[2] });
print Dumper($res);

