#!/usr/bin/perl -w

use strict;
use warnings;
use Data::Dumper;
use IOTAlib;

$| = 1;

if (scalar(@ARGV) != 4)
{
    print "Usage:\n";
    print "./gettransaction <URL> <port> <password> <hash>\n";
    print "\n";
    print "<URL> is the URL of server with IRI\n";
    print "<port> is the apiPort of IRI from configuration.iri\n";
    print "<password> is the apiPassword from configuration.iri\n";
    print "<hash> is a hash of an IOTA transaction\n";
    print "\n";
    print "Example:\n";
    print "\n";
    print "./gettransaction localhost 999 mypwd GQJQ9L9TULZBFXQ9FKTQFSWTVPEPXAHHYALVASVUOWZPJSTHVPEGP9HEZCORBIZQOTVHJUZWXSUIXY999\n";
    print "\n";
    die;
}

# --------------------------------
$IOTAlib::port = $ARGV[1];
$IOTAlib::host = $ARGV[0];

my $tips = IOTAlib::POST({    'command' => 'getTransactionsToApprove',
                                'password' => $ARGV[2] });

my $txs = IOTAlib::POST({ 'command' => 'getTransactions',
                            'hashes' => [$ARGV[3]],
                            'tips' => $tips->{'hashes'},
                            'password' => $ARGV[2] });
print Dumper($txs);

my $txsl = IOTAlib::POST({'command' => 'analyzeTransactions',
                            'trytes' => $txs->{'trytes'},
                            'password' => $ARGV[2] });
print Dumper($txsl);

